// <auto-generated />
using System;
using Chen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chen.Migrations.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Chen.Data.Entity.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnotherAdd");

                    b.Property<string>("AnotherAddTwo");

                    b.Property<string>("CreateOperator")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("LoginName");

                    b.Property<string>("Password");

                    b.Property<string>("Telephone");

                    b.Property<string>("UpdateOperator")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "9ae7401b-3c33-4402-abea-44b5caff6375",
                            CreateTime = new DateTime(2019, 1, 27, 11, 41, 25, 805, DateTimeKind.Local).AddTicks(5794),
                            LoginName = "Jacfic",
                            Password = "111111",
                            UpdateTime = new DateTime(2019, 1, 27, 11, 41, 25, 806, DateTimeKind.Local).AddTicks(5027)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
